apiVersion: v1
kind: Service
metadata:
  name: hellosvc
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 6000
  selector:
    app: helloworld
  type: LoadBalancer
